package com.tadigital.jira.plugin.constants;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class ReportsConstant {

	public ReportsConstant() {

	}

	public static Map<String, String> practices;
	public static Map<String, String> designations;
	public static List<String> notRequired;
	public static final String NONE = "None";
	public static final String PRACTICE_MANAGER_ROLE = "Practice Managers";
	public static final String PROJECT_MANAGER_ROLE = "Project Manager";
	public static final String ARCHITECT_ESTIMATES_CF = "Architect Estimate";
	public static final String DEVELOPER_CF = "Developer";
	public static final String SPRINT_CF = "Sprint";
	public static final String PRACTICE = "practice";
	public static final String BAND = "band";
	public static final String FROM = "from";
	public static final String TO = "to";
	public static final String SUB_STORY = "Sub-Story";
	public static final String STORY = "Story";
	public static final String ISSUETYPE_RELEASE = "Release";
	public static final String SUB_DEFECT = "Sub-Defect";
	public static final String BUG = "Bug";
	public static final String STATUS_OPEN = "Open";
	public static final String STATUS_DEV = "Development";
	public static final String DATE_FORMAT = "dd/MMM/yy";
	public static final String DATEPICKER_DATE_FORMAT = "yyyy-MM-dd";
	public static final String JQL_DATE_FORMAT = "yyyy/MM/dd";
	public static final String JSON_GET_DESIGNATION = "designation";
	public static final String JSON_GET_LOWERUSERNAME = "lowerUserName";
	public static final String JSON_GET_FIRSTNAME = "firstName";
	public static final String JSON_GET_LASTNAME = "lastName";
	public static final String JSON_GET_ID = "id";
	public static final String JSON_GET_BAND = "bandName";
	public static final String UTF = "UTF-8";
	public static final String ALL = "All";
	public static final String STATUS_CLOSED = "Closed";
	public static final String DELIVERY_HEAD_GROUP_NAME = "Delivery Head";
	public static final String PROJECT_MANAGER_GROUP_NAME = "Project Managers";
	public static final String ALLPRACTICES = "All Practices";
	public static final String ALLBANDS = "All Bands";
	public static final String ISSUE_LINK = "issueLinkType";
	public static final String CAUSED_BY = "is caused by";
	public static final String CAUSED_BY_DEVELOPER = "Caused by Developer";

	public static final String devBaseUrl = "https://timesheets-dev-api.tadigital.com:8076/timesheets/";
	public static final String prodBaseUrl = "https://timesheets-api.tadigital.com/timesheets/";
	public static final String employeeAPI = "/getJiraUserForGivenPracticeAndDesignation";
	public static final String bandAPI = "/getAllBands";
	public static final String practiceAPI = "/getAllPractice";
	public static final String devDeveloperAPI = "getJiraUserDetails";
	public static final String practiceBandAPI = "getJiraUserForGivenPracticeAndBand";

	public List<String> getNotRequiredList() {
		notRequired = new ArrayList<String>();
		notRequired.add("CEO");
		notRequired.add("CTO");
		notRequired.add("Senior Technical Recruiter");
		notRequired.add("Senior Vice President");
		notRequired.add("Practice Manager");
		notRequired.add("Associate - Project Manager");
		notRequired.add("Manager - Business Analysis");
		notRequired.add("Business Development Manager");
		notRequired.add("Engagement Manager - Web Technologies");
		notRequired.add("Senior Business Development Manager");
		notRequired.add("Technical Recruiter");
		notRequired.add("Director");
		notRequired.add("Associate Director");
		notRequired.add("Office Assistant ");
		notRequired.add("Vice President");
		notRequired.add("Pre-Sales Consultant");
		notRequired.add("Junior Pre-Sales Consultant ");
		notRequired.add("Quality Analyst");
		notRequired.add("Business Analyst");
		notRequired.add("Senior Business Analyst");
		notRequired.add("Management Trainee");
		notRequired.add("Senior Director");
		notRequired.add("Senior Quality Analyst");
		notRequired.add("Senior Manager - Staffing");
		notRequired.add("Senior Manager - Accounts");
		notRequired.add("Manager - Accounts");
		notRequired.add("Manager - IT ");
		notRequired.add("Associate Manager -  Talent Acquisition");
		notRequired.add("Team Lead - IT");
		notRequired.add("Principal Executive - Human Resources");
		notRequired.add("Senior Executive - Admin");
		notRequired.add("Principal Engineer - IT");
		notRequired.add("Director - Delivery");
		notRequired.add("Associate Director - QA");
		notRequired.add("Senior Network Engineer - IT");
		notRequired.add("Senior Engineer - QA");
		notRequired.add("Principal Engineer - QA");
		notRequired.add("Senior Project Manager");
		notRequired.add("Team Lead - Talent Acquisition");
		notRequired.add("Associate Manager - Admin");
		notRequired.add("Senior Executive - Human Resources");
		notRequired.add("Associate Project Manager");
		notRequired.add("Senior Executive - Business Development");
		notRequired.add("Principal Executive - Admin");
		notRequired.add("Engineer - QA");
		notRequired.add("Team Lead - QA");
		notRequired.add("Associate Executive - Admin");
		notRequired.add("Senior Executive - Talent Acquisition");
		notRequired.add("Associate Manager - QA");
		notRequired.add("Associate Technical Lead - QA");
		notRequired.add("Senior Executive - Accounts");
		notRequired.add("Executive - Admin");
		notRequired.add("Associate Director - Finance");
		notRequired.add("Executive - Human Resources");
		notRequired.add("Associate Team Lead - QA");

		notRequired.add("Director - Asia Pacific Sales");
		notRequired.add("Associate Director - Sales");
		notRequired.add("Associate Director - Human Resources");
		notRequired.add("Executive - Business Development");
		notRequired.add("Associate Executive - Talent  Acquisition");
		notRequired.add("Executive - Inside Sales");
		notRequired.add("Associate Engineer - IT");
		notRequired.add("Executive - US Accounts");
		notRequired.add("Senior Executive - US Staffing");
		notRequired.add("Project Manager");
		notRequired.add("Manager - Human Resources");
		notRequired.add("Senior Analyst - Presales");
		notRequired.add("Manager - Presales");
		notRequired.add("Senior Executive - Inside Sales");
		notRequired.add("Manager - Inside Sales");
		notRequired.add("Business Development Specialist");
		notRequired.add("Associate- Business Analyst");
		notRequired.add("Associate Executive- Inside Sales");
		notRequired.add("Executive- Immigration");
		notRequired.add("Senior Architect - DevOps");
		notRequired.add("HR Admin");
		notRequired.add("Business Development Manager");
		notRequired.add("COO");
		notRequired.add("Digital Project Manager");
		notRequired.add("Director - Digital Technologies");
		notRequired.add("Manager - Talent Acquisition");
		notRequired.add("HR Generalist");
		notRequired.add("Financial Advisor");
		notRequired.add("Advisor - Finance & Accounts");
		notRequired.add("HR Director - North America");
		notRequired.add("Account Executive");
		notRequired.add("Office Administrator");
		notRequired.add("DevOps Lead");
		notRequired.add("Human Resource Manager");
		notRequired.add("HR Assistant");
		notRequired.add("Inside Sales Director");
		notRequired.add("Vice President, Delivery");
		notRequired.add("Strategic Talent Acquisition Manager");
		notRequired.add("Sr. Practice Director");
		notRequired.add("Sr. Project Manager");
		notRequired.add("Sr. QA Analyst");
		notRequired.add("Sr. Digital Strategist");
		notRequired.add("Sr. Director");
		notRequired.add("Sr. Director, Sales");
		notRequired.add("Sr. Delivery Director");
		notRequired.add("Sr. Delivery Manager");
		notRequired.add("Sr. DevOps Engineer");
		notRequired.add("Sr. Business Analyst");
		notRequired.add("QA Analyst");
		notRequired.add("QA Lead");
		notRequired.add("Delivery Director");
		notRequired.add("DevOps Architect");
		notRequired.add("DevOps Engineer");
		notRequired.add("Director, Human Resources");
		notRequired.add("Director - Sales");
		notRequired.add("Lead Digital Strategist");
		notRequired.add("Practice VP");
		notRequired.add("Associate Digital Analyst");
		notRequired.add("Associate Digital Analyst - Intern");
		notRequired.add("Art Director");
		notRequired.add("Practice Director");
		notRequired.add("Digital Art Director");
		notRequired.add("Analyst - Intern");
		notRequired.add("Finance Controller");
		notRequired.add("Staff Accountant");
		notRequired.add("Sr. Manager, Resource Management and Operations");
		notRequired.add("Senior Director, Delivery");
		notRequired.add("Immigration Specialist");
		notRequired.add("Inside Sales Representative");
		notRequired.add("Associate Director, Delivery");
		notRequired.add("Director, Finance");
		notRequired.add("Sr. Director, Digital Commerce Channels");
		notRequired.add("Corporate Technical Recruiter");
		notRequired.add("Lead Business Analyst");
		notRequired.add("Senior Digital Analyst");
		notRequired.add("Human Resources Director");
		notRequired.add("Alliance Manager");
		notRequired.add("Sr. Sales Director - SE Region USA");
		notRequired.add("Director - Delivery West");
		notRequired.add("Director - Digital Experience & Analytics");
		notRequired.add("Digital Analyst");
		notRequired.add("Sales Director - North East");
		notRequired.add("Sales Director - South West");
		notRequired.add("Digital Strategist");
		notRequired.add("Senior Corporate Recruiter");
		notRequired.add("Senior Director Experience Design");
		notRequired.add("Senior Director - HR North America");
		notRequired.add("Financial Controller");
		notRequired.add("Resource Manager");
		notRequired.add("Senior Delivery Manager");
		notRequired.add("Delivery Manager");

		return notRequired;

	}

}
